### PR TITLE
Fixed dead links to old repo/username

### PR DESCRIPTION
**Pull request by RobRoseKnows**
I don't know whether you changed your GitHub username or if this is a clone, but the old URLs were referencing a repo that didn't exist. Fixed that for you.

### CODE REVIEW

**Comment by nickbabcock** [comment]
Good catch! The original links are from the [F# scaffold](https://github.com/fsprojects/ProjectScaffold) project that I forgot to change 🙄

**Comment by RobRoseKnows** [comment]
No problem! I've been looking into reading some of Paradox's game files and came across this. Do you know whether this works with Stellaris?

**Comment by nickbabcock** [comment]
Good question, it should as AFAIK Stellaris uses the Clausewitz engine format just like HOI4, EU4, EU3, Rome, etc.

**Comment by RobRoseKnows** [comment]
Cool, I'll have to try it it then. Originally I was planning to try to parse the tech files in Python because that's my strongest language but I might have to try to learn F# now I guess.

Most of my issue is trying to organize all the data though, as I am hoping to decode how the hell Stellaris tech files are formatted for another project. My understanding is Stellaris has a bit of a different of a tech "tree" from other Paradox games. I copied down a chunk of it [here](https://gist.github.com/RobRoseKnows/d4edbcfec3de766bde6cd7af178e56ae). Do you know how well F# works with Python?

**Comment by nickbabcock** [comment]
> I copied down a chunk of it here.

Ah yeah I already see something that isn't present in prior games (afaik):

```
years_passed > 4
```

I believe all the parsers I've written expect an equal (`=`), I'm curious what other operations are allowed 🤔 

> I might have to try to learn F# now I guess

IMO, it's not worth it for you to use this library then. You _could_ use something like IronPython to make interoperation a little easier, but I'd recommend searching out a python parser. There are typically a hodgepodge of parsers available if you search like EU4 / Paradox / Clausewitz Python.

**Pull request merged**
